{
  "arch": "arm64",
  "build": "py313hca03da5_0",
  "build_number": 0,
  "channel": "https://repo.anaconda.com/pkgs/main/osx-arm64",
  "constrains": [
    "conda >=23.9.0",
    "anaconda-cloud-auth >=0.8.2",
    "conda-token >=0.6.0"
  ],
  "depends": [
    "anaconda-cli-base >=0.5.2",
    "cryptography >=3.4.0",
    "keyring",
    "pkce",
    "pydantic",
    "pyjwt",
    "python >=3.13,<3.14.0a0",
    "python-dotenv",
    "python_abi 3.13.* *_cp313",
    "requests",
    "semver <4"
  ],
  "extracted_package_dir": "/Users/parmeetsingh/Desktop/Langchain- Projects/ENTER/pkgs/anaconda-auth-0.8.6-py313hca03da5_0",
  "files": [
    "bin/conda-token",
    "lib/python3.13/site-packages/anaconda_auth-0.8.6.dist-info/INSTALLER",
    "lib/python3.13/site-packages/anaconda_auth-0.8.6.dist-info/METADATA",
    "lib/python3.13/site-packages/anaconda_auth-0.8.6.dist-info/RECORD",
    "lib/python3.13/site-packages/anaconda_auth-0.8.6.dist-info/REQUESTED",
    "lib/python3.13/site-packages/anaconda_auth-0.8.6.dist-info/WHEEL",
    "lib/python3.13/site-packages/anaconda_auth-0.8.6.dist-info/direct_url.json",
    "lib/python3.13/site-packages/anaconda_auth-0.8.6.dist-info/entry_points.txt",
    "lib/python3.13/site-packages/anaconda_auth-0.8.6.dist-info/licenses/LICENSE",
    "lib/python3.13/site-packages/anaconda_auth/__init__.py",
    "lib/python3.13/site-packages/anaconda_auth/__main__.py",
    "lib/python3.13/site-packages/anaconda_auth/__pycache__/__init__.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/__pycache__/__main__.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/__pycache__/_version.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/__pycache__/actions.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/__pycache__/cli.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/__pycache__/client.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/__pycache__/config.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/__pycache__/exceptions.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/__pycache__/handlers.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/__pycache__/panel.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/__pycache__/repo.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/__pycache__/token.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/_conda/__init__.py",
    "lib/python3.13/site-packages/anaconda_auth/_conda/__pycache__/__init__.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/_conda/__pycache__/auth_handler.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/_conda/__pycache__/conda_token.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/_conda/__pycache__/condarc.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/_conda/__pycache__/entrypoint.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/_conda/__pycache__/plugins.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/_conda/__pycache__/repo_config.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_auth/_conda/auth_handler.py",
    "lib/python3.13/site-packages/anaconda_auth/_conda/conda_token.py",
    "lib/python3.13/site-packages/anaconda_auth/_conda/condarc.py",
    "lib/python3.13/site-packages/anaconda_auth/_conda/entrypoint.py",
    "lib/python3.13/site-packages/anaconda_auth/_conda/plugins.py",
    "lib/python3.13/site-packages/anaconda_auth/_conda/repo_config.py",
    "lib/python3.13/site-packages/anaconda_auth/_version.py",
    "lib/python3.13/site-packages/anaconda_auth/actions.py",
    "lib/python3.13/site-packages/anaconda_auth/cli.py",
    "lib/python3.13/site-packages/anaconda_auth/client.py",
    "lib/python3.13/site-packages/anaconda_auth/config.py",
    "lib/python3.13/site-packages/anaconda_auth/exceptions.py",
    "lib/python3.13/site-packages/anaconda_auth/handlers.py",
    "lib/python3.13/site-packages/anaconda_auth/panel.py",
    "lib/python3.13/site-packages/anaconda_auth/py.typed",
    "lib/python3.13/site-packages/anaconda_auth/repo.py",
    "lib/python3.13/site-packages/anaconda_auth/token.py",
    "lib/python3.13/site-packages/anaconda_cloud_auth/__init__.py",
    "lib/python3.13/site-packages/anaconda_cloud_auth/__pycache__/__init__.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_cloud_auth/__pycache__/actions.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_cloud_auth/__pycache__/cli.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_cloud_auth/__pycache__/client.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_cloud_auth/__pycache__/config.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_cloud_auth/__pycache__/exceptions.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_cloud_auth/__pycache__/handlers.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_cloud_auth/__pycache__/token.cpython-313.pyc",
    "lib/python3.13/site-packages/anaconda_cloud_auth/actions.py",
    "lib/python3.13/site-packages/anaconda_cloud_auth/cli.py",
    "lib/python3.13/site-packages/anaconda_cloud_auth/client.py",
    "lib/python3.13/site-packages/anaconda_cloud_auth/config.py",
    "lib/python3.13/site-packages/anaconda_cloud_auth/exceptions.py",
    "lib/python3.13/site-packages/anaconda_cloud_auth/handlers.py",
    "lib/python3.13/site-packages/anaconda_cloud_auth/py.typed",
    "lib/python3.13/site-packages/anaconda_cloud_auth/token.py"
  ],
  "fn": "anaconda-auth-0.8.6-py313hca03da5_0.conda",
  "license": "BSD-3-Clause",
  "license_family": "BSD",
  "link": {
    "source": "/Users/parmeetsingh/Desktop/Langchain- Projects/ENTER/pkgs/anaconda-auth-0.8.6-py313hca03da5_0",
    "type": 1
  },
  "md5": "c51a1d22828fab88aa4048b9d5281175",
  "name": "anaconda-auth",
  "package_tarball_full_path": "/Users/parmeetsingh/Desktop/Langchain- Projects/ENTER/pkgs/anaconda-auth-0.8.6-py313hca03da5_0.conda",
  "paths_data": {
    "paths": [
      {
        "_path": "bin/conda-token",
        "file_mode": "text",
        "path_type": "hardlink",
        "prefix_placeholder": "/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_c9m1keso7m/croot/anaconda-cloud-auth-split_1747863789573/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol",
        "sha256": "c79cee9563065404568718dbb66f20475f3af64dd283d1f06fa72a7fdad43944",
        "sha256_in_prefix": "155ecdf5f389d7a1c6fd84066c4b4de07e3491fc854cd50fdcccebe42b470ecc",
        "size_in_bytes": 479
      }
    ],
    "paths_version": 1
  },
  "platform": "darwin",
  "requested_spec": "defaults/osx-arm64::anaconda-auth==0.8.6=py313hca03da5_0[md5=c51a1d22828fab88aa4048b9d5281175]",
  "sha256": "2249d59ac5effab9328b2e119c588dda97e74df65a69ad82f011159f6bfe1fd5",
  "size": 88908,
  "subdir": "osx-arm64",
  "timestamp": 1747863969000,
  "url": "https://repo.anaconda.com/pkgs/main/osx-arm64/anaconda-auth-0.8.6-py313hca03da5_0.conda",
  "version": "0.8.6"
}